### ISSUE TITLE
Cannot use the framework with HDFS and OSS

### ISSUE THREAD

**Issue by rajpalparyani** [quixey/dragon-oss#1]
Hi,

I am trying to use this framework to list files in OSS (and subsequently upload files from HDFS to OSS) , but the following command returns the following error

hdfs dfs -ls oss://logshed/test1.txt
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/hadoop-2.0.0-cdh4.6.0/share/hadoop/common/lib/slf4j-log4j12-1.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/hadoop-2.0.0-cdh4.6.0/share/hadoop/hdfs/lib/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
15/07/31 12:07:45 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
-ls: Fatal internal error
com.aliyun.openservices.ClientException: The server returns an unknown error.
    at com.aliyun.openservices.oss.internal.OSSExceptionFactory.createInvalidResponseException(OSSExceptionFactory.java:28)
    at com.aliyun.openservices.oss.internal.OSSErrorResponseHandler.handle(OSSErrorResponseHandler.java:29)
    at com.aliyun.common.comm.ServiceClient.handleResponse(ServiceClient.java:284)
    at com.aliyun.common.comm.ServiceClient.sendRequestImpl(ServiceClient.java:177)
    at com.aliyun.common.comm.ServiceClient.sendRequest(ServiceClient.java:136)
    at com.aliyun.openservices.oss.internal.OSSOperation.send(OSSOperation.java:60)
    at com.aliyun.openservices.oss.internal.OSSObjectOperation.getObjectMetadata(OSSObjectOperation.java:271)
    at com.aliyun.openservices.oss.OSSClient.getObjectMetadata(OSSClient.java:411)
    at com.quixey.hadoop.fs.oss.CloudOSSFileSystemStore.retrieveMetadata(CloudOSSFileSystemStore.java:113)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:164)
    at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:83)
    at com.quixey.hadoop.fs.oss.$Proxy6.retrieveMetadata(Unknown Source)
    at com.quixey.hadoop.fs.oss.OSSFileSystem.getFileStatus(OSSFileSystem.java:491)
    at org.apache.hadoop.fs.FileSystem.globStatusInternal(FileSystem.java:1681)
    at org.apache.hadoop.fs.FileSystem.globStatus(FileSystem.java:1627)
    at org.apache.hadoop.fs.FileSystem.globStatus(FileSystem.java:1602)
    at org.apache.hadoop.fs.shell.PathData.expandAsGlob(PathData.java:271)
    at org.apache.hadoop.fs.shell.Command.expandArgument(Command.java:224)
    at org.apache.hadoop.fs.shell.Command.expandArguments(Command.java:207)
    at org.apache.hadoop.fs.shell.Command.processRawArguments(Command.java:190)
    at org.apache.hadoop.fs.shell.Command.run(Command.java:154)
    at org.apache.hadoop.fs.FsShell.run(FsShell.java:254)
    at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
    at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
    at org.apache.hadoop.fs.FsShell.main(FsShell.java:304)

I have setup the core-site.xml and hdfs-site.xml correctly. I have also verified the access key and Secret for OSS is correct. I am able to use OSS SDK 2.0.5 to list the files and get the details of the files successfully.

Please suggest ways to troubleshoot about problem..

Thanks a lot for the help.

Raj

**Comment by jonam** [comment]
http://jira.quixeyplex.com/browse/DA-1941

*Manoj Joshi *|  Senior Engineering Manager
Search OU - Data Engineering
(408) 661-0258 <http://www.quixey.com> | http://www.quixey.com
303 Bryant St, Mountain View, CA 94041

**Comment by rajpalparyani** [comment]
Any updates on this ? When would this be fixed ?

**Comment by wisematthew** [comment]
Hi rajpalparyani,

can you share your core-site.xml and hdfs-site.xml files (with credentials removed).  We will look into it.

Thanks,

Matt

**Comment by wisematthew** [comment]
HI Raj,

I started looking into your stacktrace. How are you compiling dragon-oss?  The build.gradle from master expects hadoop:2.2 on the classpath, but based on your stacktrace it looks like you're on hadoop 2.0  (Note: we haven't tested dragon-oss on Hadoop 2.0.0)

If this is the case, you can modify `build.gradle` lines 12 and 15 and change `2.2.+` to `2.0.+`, then compile and deploy as you did before.  Let us know if that solves your issue or not!

Cheers,

Matt
